### ISSUE TITLE
dropdown 相关问题

### ISSUE THREAD

**Issue by simonguo** [rsuite/rsuite-theme#2]
1.Dropdown 在展开后由于 z-index问题， Dropdown.Item 会被下面的元素
http://rsuite.github.io/#/components/dropdowns?_k=t4zlsa

可以默认z-index 都是0 ，当active后的button 设置z-index 为 1   

2.Dropdown 默认没有下边线

3.当一个link的dropdown，active以后背景是白色的，字体也是白色的，就看不见控件了
http://rsuite.github.io/#/components/dropdowns?_k=daazmb

4.dropdown 与navbar上的下拉菜单， 点击展开后的menulist 每一项的高度有点不协调
http://rsuite.github.io/#/components/navbars?_k=evhkrw

**Comment by simonguo** [comment]
1. dropdown item hover 的光标图案不对，应该是一个小手；
2. dropdown open 的时候下边有一条白色的线，实现方式可以改为border-bottom-width:0, 同时padding-bottom: +1px  实现。

**Comment by hiyangguo** [comment]
@simonguo item hover时候不是小手  因为 你的item没有href

**Comment by hiyangguo** [comment]
除`当一个link的dropdown，active以后背景是白色的`问题外均已解决
